service: hello-world

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: message
          method: get


